spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.1.162:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: sakku
  jpa:
    hibernate:
      ddl-auto: update
    
batch:
  initialize-schema: never 
      
      
      